services:
  - type: web
    name: florida-trip-log
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && node prisma/seed.js && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false # This will prompt you to paste your Postgres URL during setup
      - key: NODE_VERSION
        value: 20
